elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
    - /opt/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - /opt/logstash/config:/etc/logstash/conf.d
  ports:
    - "5600:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - /opt/kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
